version: '2.4'

services:
  cokdahakolayik:
    image: cokdahakolayapp
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cokdahakolayik
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  postgres:
    image: postgres:14.0
    restart: always
    ports:
      - 5431:5431
    environment:
      POSTGRES_DB: cokdahakolayik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  postgres_db: